#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_DIR="$(cd "${APP_DIR}/.." && pwd)"

cd "${APP_DIR}"

PYTHON_BIN=""
EXTERNAL_HOST="${HOST-}"
EXTERNAL_PORT="${PORT-}"
EXTERNAL_LOG_LEVEL="${LOG_LEVEL-}"
EXTERNAL_DATABASE_URL="${DATABASE_URL-}"
EXTERNAL_PRIMARY_LLM_BASE_URL="${PRIMARY_LLM_BASE_URL-}"
EXTERNAL_PRIMARY_LLM_MODEL_NAME="${PRIMARY_LLM_MODEL_NAME-}"
EXTERNAL_PRIMARY_LLM_API_KEY="${PRIMARY_LLM_API_KEY-}"
EXTERNAL_FALLBACK_LLM_ENABLED="${FALLBACK_LLM_ENABLED-}"
EXTERNAL_FALLBACK_LLM_BASE_URL="${FALLBACK_LLM_BASE_URL-}"
EXTERNAL_FALLBACK_LLM_MODEL_NAME="${FALLBACK_LLM_MODEL_NAME-}"
EXTERNAL_FALLBACK_LLM_API_KEY="${FALLBACK_LLM_API_KEY-}"
EXTERNAL_LLM_TIMEOUT_SECONDS="${LLM_TIMEOUT_SECONDS-}"
EXTERNAL_PRIMARY_LLM_TIMEOUT_SECONDS="${PRIMARY_LLM_TIMEOUT_SECONDS-}"
EXTERNAL_ROUTINE_PROFILE_TIMEOUT_SECONDS="${ROUTINE_PROFILE_TIMEOUT_SECONDS-}"
EXTERNAL_LLM_HEALTH_TIMEOUT_SECONDS="${LLM_HEALTH_TIMEOUT_SECONDS-}"
EXTERNAL_LLM_MAX_RETRIES="${LLM_MAX_RETRIES-}"
EXTERNAL_LLM_MAX_TOKENS="${LLM_MAX_TOKENS-}"
EXTERNAL_ROUTINE_PROFILE_MAX_TOKENS="${ROUTINE_PROFILE_MAX_TOKENS-}"
EXTERNAL_LLM_TEMPERATURE="${LLM_TEMPERATURE-}"
EXTERNAL_REQUEST_DEADLINE_SECONDS="${REQUEST_DEADLINE_SECONDS-}"
EXTERNAL_ROUTINE_DAY_DETAIL_TIMEOUT_SECONDS="${ROUTINE_DAY_DETAIL_TIMEOUT_SECONDS-}"

if [ -f "${REPO_DIR}/.venv/bin/activate" ]; then
  # shellcheck disable=SC1091
  source "${REPO_DIR}/.venv/bin/activate"
  PYTHON_BIN="${REPO_DIR}/.venv/bin/python"
fi

if [ -f "${APP_DIR}/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "${APP_DIR}/.env"
  set +a
fi

if [ -n "${EXTERNAL_HOST}" ]; then
  HOST="${EXTERNAL_HOST}"
fi

if [ -n "${EXTERNAL_PORT}" ]; then
  PORT="${EXTERNAL_PORT}"
fi

if [ -n "${EXTERNAL_LOG_LEVEL}" ]; then
  LOG_LEVEL="${EXTERNAL_LOG_LEVEL}"
fi

if [ -n "${EXTERNAL_DATABASE_URL}" ]; then
  DATABASE_URL="${EXTERNAL_DATABASE_URL}"
fi

if [ -n "${EXTERNAL_PRIMARY_LLM_BASE_URL}" ]; then
  PRIMARY_LLM_BASE_URL="${EXTERNAL_PRIMARY_LLM_BASE_URL}"
fi

if [ -n "${EXTERNAL_PRIMARY_LLM_MODEL_NAME}" ]; then
  PRIMARY_LLM_MODEL_NAME="${EXTERNAL_PRIMARY_LLM_MODEL_NAME}"
fi

if [ -n "${EXTERNAL_PRIMARY_LLM_API_KEY}" ]; then
  PRIMARY_LLM_API_KEY="${EXTERNAL_PRIMARY_LLM_API_KEY}"
fi

if [ -n "${EXTERNAL_FALLBACK_LLM_ENABLED}" ]; then
  FALLBACK_LLM_ENABLED="${EXTERNAL_FALLBACK_LLM_ENABLED}"
fi

if [ -n "${EXTERNAL_FALLBACK_LLM_BASE_URL}" ]; then
  FALLBACK_LLM_BASE_URL="${EXTERNAL_FALLBACK_LLM_BASE_URL}"
fi

if [ -n "${EXTERNAL_FALLBACK_LLM_MODEL_NAME}" ]; then
  FALLBACK_LLM_MODEL_NAME="${EXTERNAL_FALLBACK_LLM_MODEL_NAME}"
fi

if [ -n "${EXTERNAL_FALLBACK_LLM_API_KEY}" ]; then
  FALLBACK_LLM_API_KEY="${EXTERNAL_FALLBACK_LLM_API_KEY}"
fi

if [ -n "${EXTERNAL_LLM_TIMEOUT_SECONDS}" ]; then
  LLM_TIMEOUT_SECONDS="${EXTERNAL_LLM_TIMEOUT_SECONDS}"
fi

if [ -n "${EXTERNAL_PRIMARY_LLM_TIMEOUT_SECONDS}" ]; then
  PRIMARY_LLM_TIMEOUT_SECONDS="${EXTERNAL_PRIMARY_LLM_TIMEOUT_SECONDS}"
fi

if [ -n "${EXTERNAL_ROUTINE_PROFILE_TIMEOUT_SECONDS}" ]; then
  ROUTINE_PROFILE_TIMEOUT_SECONDS="${EXTERNAL_ROUTINE_PROFILE_TIMEOUT_SECONDS}"
fi

if [ -n "${EXTERNAL_LLM_HEALTH_TIMEOUT_SECONDS}" ]; then
  LLM_HEALTH_TIMEOUT_SECONDS="${EXTERNAL_LLM_HEALTH_TIMEOUT_SECONDS}"
fi

if [ -n "${EXTERNAL_LLM_MAX_RETRIES}" ]; then
  LLM_MAX_RETRIES="${EXTERNAL_LLM_MAX_RETRIES}"
fi

if [ -n "${EXTERNAL_LLM_MAX_TOKENS}" ]; then
  LLM_MAX_TOKENS="${EXTERNAL_LLM_MAX_TOKENS}"
fi

if [ -n "${EXTERNAL_ROUTINE_PROFILE_MAX_TOKENS}" ]; then
  ROUTINE_PROFILE_MAX_TOKENS="${EXTERNAL_ROUTINE_PROFILE_MAX_TOKENS}"
fi

if [ -n "${EXTERNAL_LLM_TEMPERATURE}" ]; then
  LLM_TEMPERATURE="${EXTERNAL_LLM_TEMPERATURE}"
fi

if [ -n "${EXTERNAL_REQUEST_DEADLINE_SECONDS}" ]; then
  REQUEST_DEADLINE_SECONDS="${EXTERNAL_REQUEST_DEADLINE_SECONDS}"
fi

if [ -n "${EXTERNAL_ROUTINE_DAY_DETAIL_TIMEOUT_SECONDS}" ]; then
  ROUTINE_DAY_DETAIL_TIMEOUT_SECONDS="${EXTERNAL_ROUTINE_DAY_DETAIL_TIMEOUT_SECONDS}"
fi

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-7000}"
LOG_LEVEL="${LOG_LEVEL:-info}"

if [ -z "${PYTHON_BIN}" ] || [ ! -x "${PYTHON_BIN}" ]; then
  echo "루트 가상환경을 찾지 못했습니다: ${REPO_DIR}/.venv/bin/python" >&2
  exit 127
fi

exec "${PYTHON_BIN}" -m uvicorn app.main:app --host "${HOST}" --port "${PORT}" --log-level "${LOG_LEVEL}"
